# Generated by Django 3.0 on 2020-08-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
