# Generated by Django 3.0 on 2020-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='items_ids',
            field=models.CharField(default='item', max_length=255),
        ),
    ]
